# Generated by Django 3.1.1 on 2020-09-28 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitize_invoice', '0003_digitizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='digitizer',
            name='id',
        ),
        migrations.AlterField(
            model_name='digitizer',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='digitize_invoice.invoice'),
        ),
    ]
