# Generated by Django 3.1.1 on 2020-09-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitize_invoice', '0005_auto_20200928_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitizer',
            name='digitized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
